# Generated by Django 3.0.6 on 2020-05-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20200528_2345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
