# Generated by Django 3.0.6 on 2020-05-29 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PName', models.CharField(max_length=100)),
                ('PAge', models.IntegerField()),
                ('PType', models.CharField(max_length=150)),
                ('TeamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Teams')),
            ],
        ),
    ]
