# Generated by Django 3.0.6 on 2020-05-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='TeamLogo',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
