# Generated by Django 3.0.6 on 2020-05-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_teams_teamlogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='TeamLogo',
        ),
    ]
