# Generated by Django 3.0.6 on 2020-05-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_remove_teams_teamlogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='PName',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
