# Generated by Django 3.0.6 on 2020-05-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20200530_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='PID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='PName',
            field=models.CharField(max_length=100),
        ),
    ]
